export enum EventType {
  CURSO = 'CURSO',
  DIPLOMADO = 'DIPLOMADO',
  TALLER = 'TALLER',
  SEMINARIO = 'SEMINARIO',
  CONFERENCIA = 'CONFERENCIA',
  CONGRESO = 'CONGRESO',
  FORO = 'FORO',
  SIMPOSIO = 'SIMPOSIO',
  PANEL = 'PANEL',
}