services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-gestion-eventos-api
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped
